language: node_js
sudo: false

services:
  - postgresql

addons:
  postgresql: "9.5"

node_js:
  - '0.10'

before_script:
  - psql -c 'create database test_travis_ci;' -U postgres

script:
  - npm run test-ci

branches:
  only:
    - master
    - dev
    - /^feature-.*$/
    - /^issue-*$/
    - /^hotfix-*$/
    - /^fix-*$/